### ISSUE TITLE
Dates with lat/lon

### ISSUE THREAD

**Issue by jduckles** [tags/geologgerui#5]
Figure out a way to associate dates with locations.

Simeon suggests using the midpoint between the two twilights as the date for a given location.

**Comment by phildow** [comment]
Had a meeting with Eli, will be knocking the bugs off this list over the next couple weeks. Looks like most (all?) of the work should be client side. But you'll know if not!

And yeah, this is one of them. Piece of cake to fix.

**Comment by jduckles** [comment]
MoveBank is itching to integrate TAGS with their stuff.  You have the file formats and stuff locked down?  Or are there changes that are coming?

**Comment by kfranks** [comment]
I can work on it today. Do you think you could help me get started?

On Oct 3, 2013, at 8:41 AM, "Jonah Duckles" <notifications@github.com<mailto:notifications@github.com>> wrote:

MoveBank is itching to integrate TAGS with their stuff. You have the file formats and stuff locked down? Or are there changes that are coming?

**Comment by phildow** [comment]
I still want to wrap everything up. I know it's manana, manana, but I'm finally submitting Xiangming's app and my other client's app to the app store Frida. Monday! I swear! Egh.

**Comment by kfranks** [comment]
Okay that's no problem!! I will just continue to work on JQueary stuff.

On Oct 3, 2013, at 10:04 AM, "Philip Dow" <notifications@github.com<mailto:notifications@github.com>> wrote:

I still want to wrap everything up. I know it's manana, manana, but I'm finally submitting Xiangming's app and my other client's app to the app store Frida. Monday! I swear! Egh.
